apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  name: gohome

resources:
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml

images:
  - name: ghcr.io/joeds13/gohome
    newTag: latest

namespace: gohome

replicas:
  - count: 1
    name: gohome

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: home.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: home.example.com
    target:
      kind: Ingress
      name: gohome

labels:
  - includeSelectors: true
    pairs:
      app: gohome
      app.kubernetes.io/component: web
      app.kubernetes.io/name: gohome
      app.kubernetes.io/part-of: gohome
