---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gohome
  namespace: default
  labels:
    app: gohome

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gohome-reader
  labels:
    app: gohome
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gohome-reader-binding
  labels:
    app: gohome
subjects:
  - kind: ServiceAccount
    name: gohome
    namespace: default
roleRef:
  kind: ClusterRole
  name: gohome-reader
  apiGroup: rbac.authorization.k8s.io
